# Generated by Django 4.2.20 on 2025-04-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_note_notevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='events.event'),
        ),
    ]
