# Generated by Django 4.2.20 on 2025-04-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_note_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.target'),
        ),
        migrations.AddField(
            model_name='note',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='related_notes', to='events.event'),
        ),
        migrations.AddField(
            model_name='note',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='events.target'),
        ),
    ]
