# Generated by Django 4.2.20 on 2025-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the event (recommended ratio 2:3)', null=True, upload_to='event_images/'),
        ),
    ]
