# Generated by Django 4.2.20 on 2025-04-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_is_public_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If checked, all users can see this note'),
        ),
    ]
